### ISSUE TITLE
aes key不能用64位或128位加密

### ISSUE THREAD

**Issue by simon-muyezhang** [staugur/Python-SecureHTTP#2]
你好，
请问我为什么不能用64位以及128位加密。
我看文档上写是16的倍数就行了，这里边也是取16的倍数。
为什么我的key是64位就报错。
![D )G$L(_IPX0I9ZH8)H5IIP](https://user-images.githubusercontent.com/10706610/56626304-c68e5680-6673-11e9-989c-f8434eb2d1b2.png)

![~QDB_I}93E93}J31QL~2 O](https://user-images.githubusercontent.com/10706610/56626277-a068b680-6673-11e9-81e6-e8d4342e903d.png)

**Comment by staugur** [comment]
Bug，目前采用的AES库，[https://www.pycryptodome.org/en/latest/src/cipher/aes.html#Crypto.Cipher.AES.new](https://www.pycryptodome.org/en/latest/src/cipher/aes.html#Crypto.Cipher.AES.new)，key长度要求16、24、32字节，对应AES128、AES192、AES256，目前key长度判断有误，将发布新版修复。

**Comment by staugur** [comment]
@simon-zhangmuye 可更新到0.5.0
